// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VSOSH.Dal;

#nullable disable

namespace VSOSH.Dal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VSOSH.Domain.Entities.GeneralReport", b =>
                {
                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("TotalCount");

                    b.Property<int>("TotalPrizeDiplomas")
                        .HasColumnType("integer")
                        .HasColumnName("TotalPrizeDiplomas");

                    b.Property<int>("TotalWinnerDiplomas")
                        .HasColumnType("integer")
                        .HasColumnName("TotalWinnerDiplomas");

                    b.Property<int>("UniqueParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("UniqueParticipants");

                    b.Property<int>("UniquePrizeWinners")
                        .HasColumnType("integer")
                        .HasColumnName("UniquePrizeWinners");

                    b.Property<int>("UniqueWinners")
                        .HasColumnType("integer")
                        .HasColumnName("UniqueWinners");

                    b.Property<int>("UniqueWinnersAndPrizeWinners")
                        .HasColumnType("integer")
                        .HasColumnName("UniqueWinnersAndPrizeWinners");

                    b.ToTable((string)null);

                    b.ToView("GeneralReportView", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.SchoolOlympiadResultBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentCompeting")
                        .HasColumnType("integer")
                        .HasColumnName("CurrentGrade");

                    b.Property<double>("FinalScore")
                        .HasColumnType("double precision");

                    b.Property<int>("GradeCompeting")
                        .HasColumnType("integer")
                        .HasColumnName("GradeCompeting");

                    b.Property<string>("ParticipantCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ParticipantCode");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("Percentage");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("School");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.ComplexProperty<Dictionary<string, object>>("StudentName", "VSOSH.Domain.Entities.SchoolOlympiadResultBase.StudentName#StudentName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MiddleName");
                        });

                    b.HasKey("Id");

                    b.ToTable("SchoolOlympiadResultBase", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.ArtResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("ArtResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.AstronomyResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("AstronomyResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.BiologyResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("BiologyResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.ChemistryResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("ChemistryResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.ChineseResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("ChineseResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.ComputerScienceResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("ComputerScienceResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.EcologyResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("EcologyResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.EconomyResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("EconomyResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.EnglishResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("EnglishResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.FrenchResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("FrenchResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.FundamentalsLifeSafetyResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("FundamentalsLifeSafetyResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.GeographyResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("GeographyResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.GermanResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("GermanResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.HistoryResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("HistoryResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.LawResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("LawResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.LiteratureResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("LiteratureResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.MathResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("MathResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.PhysicResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("PhysicResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.PhysicalEducationResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.Property<double>("FinalScoreInPractice")
                        .HasColumnType("double precision")
                        .HasColumnName("FinalScoreInPractice");

                    b.Property<double>("FinalScoreInTheory")
                        .HasColumnType("double precision")
                        .HasColumnName("FinalScoreInTheory");

                    b.Property<double>("PreliminaryScoreInPractice")
                        .HasColumnType("double precision")
                        .HasColumnName("PreliminaryScoreInPractice");

                    b.Property<double>("PreliminaryScoreInTheory")
                        .HasColumnType("double precision")
                        .HasColumnName("PreliminaryScoreInTheory");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Sex");

                    b.ToTable("PhysicalEducationResult", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.RussianResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("RussianResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.SocialStudiesResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.ToTable("SocialStudiesResults", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.TechnologyResult", b =>
                {
                    b.HasBaseType("VSOSH.Domain.Entities.SchoolOlympiadResultBase");

                    b.Property<string>("DirectionPractice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DirectionPractice");

                    b.ToTable("TechnologyResult", (string)null);
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.ArtResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.ArtResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.AstronomyResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.AstronomyResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.BiologyResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.BiologyResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.ChemistryResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.ChemistryResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.ChineseResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.ChineseResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.ComputerScienceResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.ComputerScienceResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.EcologyResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.EcologyResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.EconomyResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.EconomyResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.EnglishResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.EnglishResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.FrenchResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.FrenchResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.FundamentalsLifeSafetyResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.FundamentalsLifeSafetyResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.GeographyResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.GeographyResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.GermanResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.GermanResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.HistoryResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.HistoryResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.LawResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.LawResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.LiteratureResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.LiteratureResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.MathResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.MathResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.PhysicResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.PhysicResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.PhysicalEducationResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.PhysicalEducationResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.RussianResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.RussianResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.SocialStudiesResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.SocialStudiesResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VSOSH.Domain.Entities.TechnologyResult", b =>
                {
                    b.HasOne("VSOSH.Domain.Entities.SchoolOlympiadResultBase", null)
                        .WithOne()
                        .HasForeignKey("VSOSH.Domain.Entities.TechnologyResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
